# AUTO GENERATED FILE - DO NOT EDIT

''DashTabulator <- function(id=NULL, ajaxError=NULL, ajaxRequesting=NULL, ajaxResponse=NULL, cellClicked=NULL, cellContext=NULL, cellDblClick=NULL, cellDblTap=NULL, cellEditCancelled=NULL, cellEdited=NULL, cellEditing=NULL, cellTap=NULL, cellTapHold=NULL, clearFilterButtonType=NULL, clipboardCopied=NULL, clipboardPasteError=NULL, clipboardPasted=NULL, columnMoved=NULL, columnResized=NULL, columnTitleChanged=NULL, columnVisibilityChanged=NULL, columns=NULL, data=NULL, dataChanged=NULL, dataFiltered=NULL, dataFiltering=NULL, dataGrouped=NULL, dataGrouping=NULL, dataLoaded=NULL, dataLoading=NULL, dataSorted=NULL, dataSorting=NULL, downloadButtonType=NULL, downloadComplete=NULL, downloadReady=NULL, groupClick=NULL, groupContext=NULL, groupDblClick=NULL, groupDblTap=NULL, groupTap=NULL, groupTapHold=NULL, groupVisibilityChanged=NULL, headerClick=NULL, headerContext=NULL, headerDblClick=NULL, headerDblTap=NULL, headerTap=NULL, headerTapHold=NULL, htmlImported=NULL, htmlImporting=NULL, initialHeaderFilter=NULL, localized=NULL, movableRowsReceived=NULL, movableRowsReceivedFailed=NULL, movableRowsReceivingStart=NULL, movableRowsReceivingStop=NULL, movableRowsSendingStart=NULL, movableRowsSendingStop=NULL, movableRowsSent=NULL, movableRowsSentFailed=NULL, multiRowsClicked=NULL, options=NULL, pageLoaded=NULL, renderComplete=NULL, renderStarted=NULL, rowAdded=NULL, rowClick=NULL, rowClicked=NULL, rowContext=NULL, rowDblClick=NULL, rowDblTap=NULL, rowDeleted=NULL, rowDeselected=NULL, rowMoved=NULL, rowResized=NULL, rowSelected=NULL, rowSelectionChanged=NULL, rowTap=NULL, rowTapHold=NULL, rowUpdated=NULL, selectableCheck=NULL, tableBuilding=NULL, tableBuilt=NULL, theme=NULL, validationFailed=NULL) {
    
    props <- list(id=id, ajaxError=ajaxError, ajaxRequesting=ajaxRequesting, ajaxResponse=ajaxResponse, cellClicked=cellClicked, cellContext=cellContext, cellDblClick=cellDblClick, cellDblTap=cellDblTap, cellEditCancelled=cellEditCancelled, cellEdited=cellEdited, cellEditing=cellEditing, cellTap=cellTap, cellTapHold=cellTapHold, clearFilterButtonType=clearFilterButtonType, clipboardCopied=clipboardCopied, clipboardPasteError=clipboardPasteError, clipboardPasted=clipboardPasted, columnMoved=columnMoved, columnResized=columnResized, columnTitleChanged=columnTitleChanged, columnVisibilityChanged=columnVisibilityChanged, columns=columns, data=data, dataChanged=dataChanged, dataFiltered=dataFiltered, dataFiltering=dataFiltering, dataGrouped=dataGrouped, dataGrouping=dataGrouping, dataLoaded=dataLoaded, dataLoading=dataLoading, dataSorted=dataSorted, dataSorting=dataSorting, downloadButtonType=downloadButtonType, downloadComplete=downloadComplete, downloadReady=downloadReady, groupClick=groupClick, groupContext=groupContext, groupDblClick=groupDblClick, groupDblTap=groupDblTap, groupTap=groupTap, groupTapHold=groupTapHold, groupVisibilityChanged=groupVisibilityChanged, headerClick=headerClick, headerContext=headerContext, headerDblClick=headerDblClick, headerDblTap=headerDblTap, headerTap=headerTap, headerTapHold=headerTapHold, htmlImported=htmlImported, htmlImporting=htmlImporting, initialHeaderFilter=initialHeaderFilter, localized=localized, movableRowsReceived=movableRowsReceived, movableRowsReceivedFailed=movableRowsReceivedFailed, movableRowsReceivingStart=movableRowsReceivingStart, movableRowsReceivingStop=movableRowsReceivingStop, movableRowsSendingStart=movableRowsSendingStart, movableRowsSendingStop=movableRowsSendingStop, movableRowsSent=movableRowsSent, movableRowsSentFailed=movableRowsSentFailed, multiRowsClicked=multiRowsClicked, options=options, pageLoaded=pageLoaded, renderComplete=renderComplete, renderStarted=renderStarted, rowAdded=rowAdded, rowClick=rowClick, rowClicked=rowClicked, rowContext=rowContext, rowDblClick=rowDblClick, rowDblTap=rowDblTap, rowDeleted=rowDeleted, rowDeselected=rowDeselected, rowMoved=rowMoved, rowResized=rowResized, rowSelected=rowSelected, rowSelectionChanged=rowSelectionChanged, rowTap=rowTap, rowTapHold=rowTapHold, rowUpdated=rowUpdated, selectableCheck=selectableCheck, tableBuilding=tableBuilding, tableBuilt=tableBuilt, theme=theme, validationFailed=validationFailed)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'DashTabulator',
        namespace = 'dash_tabulator',
        propNames = c('id', 'ajaxError', 'ajaxRequesting', 'ajaxResponse', 'cellClicked', 'cellContext', 'cellDblClick', 'cellDblTap', 'cellEditCancelled', 'cellEdited', 'cellEditing', 'cellTap', 'cellTapHold', 'clearFilterButtonType', 'clipboardCopied', 'clipboardPasteError', 'clipboardPasted', 'columnMoved', 'columnResized', 'columnTitleChanged', 'columnVisibilityChanged', 'columns', 'data', 'dataChanged', 'dataFiltered', 'dataFiltering', 'dataGrouped', 'dataGrouping', 'dataLoaded', 'dataLoading', 'dataSorted', 'dataSorting', 'downloadButtonType', 'downloadComplete', 'downloadReady', 'groupClick', 'groupContext', 'groupDblClick', 'groupDblTap', 'groupTap', 'groupTapHold', 'groupVisibilityChanged', 'headerClick', 'headerContext', 'headerDblClick', 'headerDblTap', 'headerTap', 'headerTapHold', 'htmlImported', 'htmlImporting', 'initialHeaderFilter', 'localized', 'movableRowsReceived', 'movableRowsReceivedFailed', 'movableRowsReceivingStart', 'movableRowsReceivingStop', 'movableRowsSendingStart', 'movableRowsSendingStop', 'movableRowsSent', 'movableRowsSentFailed', 'multiRowsClicked', 'options', 'pageLoaded', 'renderComplete', 'renderStarted', 'rowAdded', 'rowClick', 'rowClicked', 'rowContext', 'rowDblClick', 'rowDblTap', 'rowDeleted', 'rowDeselected', 'rowMoved', 'rowResized', 'rowSelected', 'rowSelectionChanged', 'rowTap', 'rowTapHold', 'rowUpdated', 'selectableCheck', 'tableBuilding', 'tableBuilt', 'theme', 'validationFailed'),
        package = 'dashTabulator'
        )

    structure(component, class = c('dash_component', 'list'))
}
