# AUTO GENERATED FILE - DO NOT EDIT

dashTabulator <- function(id=NULL, columns=NULL, data=NULL, options=NULL, rowClicked=NULL, multiRowsClicked=NULL, cellEdited=NULL, dataChanged=NULL, downloadButtonType=NULL, clearFilterButtonType=NULL, initialHeaderFilter=NULL, dataFiltering=NULL, dataFiltered=NULL, rowClick=NULL, tableBuilding=NULL, tableBuilt=NULL, rowDblClick=NULL, rowContext=NULL, rowTap=NULL, rowDblTap=NULL, rowTapHold=NULL, rowAdded=NULL, rowDeleted=NULL, rowMoved=NULL, rowUpdated=NULL, rowSelectionChanged=NULL, rowSelected=NULL, rowDeselected=NULL, rowResized=NULL, cellClick=NULL, cellDblClick=NULL, cellContext=NULL, cellTap=NULL, cellDblTap=NULL, cellTapHold=NULL, cellEditing=NULL, cellEditCancelled=NULL, columnMoved=NULL, columnResized=NULL, columnTitleChanged=NULL, columnVisibilityChanged=NULL, headerClick=NULL, headerDblClick=NULL, headerContext=NULL, headerTap=NULL, headerDblTap=NULL, headerTapHold=NULL, htmlImporting=NULL, htmlImported=NULL, dataLoading=NULL, dataLoaded=NULL, ajaxRequesting=NULL, ajaxResponse=NULL, ajaxError=NULL, dataSorting=NULL, dataSorted=NULL, renderStarted=NULL, renderComplete=NULL, pageLoaded=NULL, localized=NULL, dataGrouping=NULL, dataGrouped=NULL, groupVisibilityChanged=NULL, groupClick=NULL, groupDblClick=NULL, groupContext=NULL, groupTap=NULL, groupDblTap=NULL, groupTapHold=NULL, movableRowsSendingStart=NULL, movableRowsSent=NULL, movableRowsSentFailed=NULL, movableRowsSendingStop=NULL, movableRowsReceivingStart=NULL, movableRowsReceived=NULL, movableRowsReceivedFailed=NULL, movableRowsReceivingStop=NULL, validationFailed=NULL, clipboardCopied=NULL, clipboardPasted=NULL, clipboardPasteError=NULL, downloadReady=NULL, downloadComplete=NULL, selectableCheck=NULL) {
    
    props <- list(id=id, columns=columns, data=data, options=options, rowClicked=rowClicked, multiRowsClicked=multiRowsClicked, cellEdited=cellEdited, dataChanged=dataChanged, downloadButtonType=downloadButtonType, clearFilterButtonType=clearFilterButtonType, initialHeaderFilter=initialHeaderFilter, dataFiltering=dataFiltering, dataFiltered=dataFiltered, rowClick=rowClick, tableBuilding=tableBuilding, tableBuilt=tableBuilt, rowDblClick=rowDblClick, rowContext=rowContext, rowTap=rowTap, rowDblTap=rowDblTap, rowTapHold=rowTapHold, rowAdded=rowAdded, rowDeleted=rowDeleted, rowMoved=rowMoved, rowUpdated=rowUpdated, rowSelectionChanged=rowSelectionChanged, rowSelected=rowSelected, rowDeselected=rowDeselected, rowResized=rowResized, cellClick=cellClick, cellDblClick=cellDblClick, cellContext=cellContext, cellTap=cellTap, cellDblTap=cellDblTap, cellTapHold=cellTapHold, cellEditing=cellEditing, cellEditCancelled=cellEditCancelled, columnMoved=columnMoved, columnResized=columnResized, columnTitleChanged=columnTitleChanged, columnVisibilityChanged=columnVisibilityChanged, headerClick=headerClick, headerDblClick=headerDblClick, headerContext=headerContext, headerTap=headerTap, headerDblTap=headerDblTap, headerTapHold=headerTapHold, htmlImporting=htmlImporting, htmlImported=htmlImported, dataLoading=dataLoading, dataLoaded=dataLoaded, ajaxRequesting=ajaxRequesting, ajaxResponse=ajaxResponse, ajaxError=ajaxError, dataSorting=dataSorting, dataSorted=dataSorted, renderStarted=renderStarted, renderComplete=renderComplete, pageLoaded=pageLoaded, localized=localized, dataGrouping=dataGrouping, dataGrouped=dataGrouped, groupVisibilityChanged=groupVisibilityChanged, groupClick=groupClick, groupDblClick=groupDblClick, groupContext=groupContext, groupTap=groupTap, groupDblTap=groupDblTap, groupTapHold=groupTapHold, movableRowsSendingStart=movableRowsSendingStart, movableRowsSent=movableRowsSent, movableRowsSentFailed=movableRowsSentFailed, movableRowsSendingStop=movableRowsSendingStop, movableRowsReceivingStart=movableRowsReceivingStart, movableRowsReceived=movableRowsReceived, movableRowsReceivedFailed=movableRowsReceivedFailed, movableRowsReceivingStop=movableRowsReceivingStop, validationFailed=validationFailed, clipboardCopied=clipboardCopied, clipboardPasted=clipboardPasted, clipboardPasteError=clipboardPasteError, downloadReady=downloadReady, downloadComplete=downloadComplete, selectableCheck=selectableCheck)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'DashTabulator',
        namespace = 'dash_tabulator',
        propNames = c('id', 'columns', 'data', 'options', 'rowClicked', 'multiRowsClicked', 'cellEdited', 'dataChanged', 'downloadButtonType', 'clearFilterButtonType', 'initialHeaderFilter', 'dataFiltering', 'dataFiltered', 'rowClick', 'tableBuilding', 'tableBuilt', 'rowDblClick', 'rowContext', 'rowTap', 'rowDblTap', 'rowTapHold', 'rowAdded', 'rowDeleted', 'rowMoved', 'rowUpdated', 'rowSelectionChanged', 'rowSelected', 'rowDeselected', 'rowResized', 'cellClick', 'cellDblClick', 'cellContext', 'cellTap', 'cellDblTap', 'cellTapHold', 'cellEditing', 'cellEditCancelled', 'columnMoved', 'columnResized', 'columnTitleChanged', 'columnVisibilityChanged', 'headerClick', 'headerDblClick', 'headerContext', 'headerTap', 'headerDblTap', 'headerTapHold', 'htmlImporting', 'htmlImported', 'dataLoading', 'dataLoaded', 'ajaxRequesting', 'ajaxResponse', 'ajaxError', 'dataSorting', 'dataSorted', 'renderStarted', 'renderComplete', 'pageLoaded', 'localized', 'dataGrouping', 'dataGrouped', 'groupVisibilityChanged', 'groupClick', 'groupDblClick', 'groupContext', 'groupTap', 'groupDblTap', 'groupTapHold', 'movableRowsSendingStart', 'movableRowsSent', 'movableRowsSentFailed', 'movableRowsSendingStop', 'movableRowsReceivingStart', 'movableRowsReceived', 'movableRowsReceivedFailed', 'movableRowsReceivingStop', 'validationFailed', 'clipboardCopied', 'clipboardPasted', 'clipboardPasteError', 'downloadReady', 'downloadComplete', 'selectableCheck'),
        package = 'dashTabulator'
        )

    structure(component, class = c('dash_component', 'list'))
}
